import { NextResponse } from "next/server";

const items = [
  {
    id: "1",
    ref: "BLANCH-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Blanchiment Dentaire",
    description: "Traitement de blanchiment professionnel pour un sourire éclatant.",
    price: 100,
    stock: 15,
    mark: "Premium",
    tags: ["A"],
    category: "Services Spécialisés",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01")
  },
  {
    id: "2",
    ref: "IMPLANT-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Implant Dentaire",
    description: "Solution permanente pour dents manquantes.",
    price: 450,
    new_price: 399,
    stock: 0,
    mark: "Standard",
    tags: ["B"],
    category: "Chirurgie Dentaire",
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-02")
  },
  {
    id: "3",
    ref: "ORTHO-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Orthodontie Invisible",
    description: "Aligne vos dents discrètement avec des gouttières transparentes.",
    price: 600,
    stock: 12,
    mark: "Premium",
    tags: ["C"],
    category: "Orthodontie",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03")
  },
  {
    id: "4",
    ref: "DETART-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Détartrage",
    description: "Élimination du tartre pour une hygiène buccale optimale.",
    price: 70,
    new_price: 50,
    stock: 25,
    mark: "Basic",
    tags: ["A"],
    category: "Soins Préventifs",
    createdAt: new Date("2024-01-04"),
    updatedAt: new Date("2024-01-04")
  },
  {
    id: "5",
    ref: "FACETTE-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Facette Dentaire",
    description: "Améliorez votre sourire avec des facettes esthétiques.",
    price: 800,
    stock: 6,
    mark: "Luxury",
    tags: ["E"],
    category: "Services Spécialisés",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05")
  },
  {
    id: "6",
    ref: "DEVITAL-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Dévitalisation",
    description: "Traitement de canal pour dents endommagées.",
    price: 200,
    new_price: 180,
    stock: 10,
    mark: "Standard",
    tags: ["C"],
    category: "Chirurgie Dentaire",
    createdAt: new Date("2024-01-06"),
    updatedAt: new Date("2024-01-06")
  },
  {
    id: "7",
    ref: "BRIDGE-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Bridge Dentaire",
    description: "Remplace les dents manquantes avec un pont fixe.",
    price: 700,
    new_price: 650,
    stock: 0,
    mark: "Premium",
    tags: ["B"],
    category: "Prothèses",
    createdAt: new Date("2024-01-07"),
    updatedAt: new Date("2024-01-07")
  },
  {
    id: "8",
    ref: "COURONNE-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Couronne Céramique",
    description: "Protège et restaure les dents abîmées.",
    price: 500,
    new_price: 450,
    stock: 18,
    mark: "Standard",
    tags: ["D"],
    category: "Prothèses",
    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-08")
  },
  {
    id: "9",
    ref: "COMPOSITE-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Composite Esthétique",
    description: "Restaurations dentaires avec résines modernes.",
    price: 120,
    new_price: 100,
    stock: 30,
    mark: "Basic",
    tags: ["D"],
    category: "Services Spécialisés",
    createdAt: new Date("2024-01-09"),
    updatedAt: new Date("2024-01-09")
  },
  {
    id: "10",
    ref: "NETTOYAGE-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Nettoyage Complet",
    description: "Nettoyage, polissage et fluor pour une bouche saine.",
    price: 90,
    new_price: 75,
    stock: 20,
    mark: "Basic",
    tags: ["A"],
    category: "Soins Préventifs",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10")
  },
  {
    id: "11",
    ref: "RADIO-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Radiographie Dentaire",
    description: "Imagerie numérique pour un diagnostic précis.",
    price: 50,
    new_price: 40,
    stock: 35,
    mark: "Basic",
    tags: ["E"],
    category: "Services Spécialisés",
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-11")
  },
  {
    id: "12",
    ref: "EXTRACTION-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Extraction Dentaire",
    description: "Extraction rapide et sans douleur des dents.",
    price: 90,
    new_price: 70,
    stock: 14,
    mark: "Standard",
    tags: ["C"],
    category: "Chirurgie Dentaire",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12")
  },
  {
    id: "13",
    ref: "PROTHESE-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Prothèse Dentaire",
    description: "Appareil amovible pour remplacer plusieurs dents.",
    price: 300,
    new_price: 280,
    stock: 7,
    mark: "Standard",
    tags: ["D"],
    category: "Prothèses",
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-13")
  },
  {
    id: "14",
    ref: "INLAY-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Inlay / Onlay",
    description: "Alternative aux couronnes pour dents partiellement abîmées.",
    price: 250,
    new_price: 220,
    stock: 11,
    mark: "Standard",
    tags: ["C"],
    category: "Prothèses",
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14")
  },
  {
    id: "15",
    ref: "GENCIVES-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Traitement des gencives",
    description: "Traitement des infections gingivales chroniques.",
    price: 150,
    new_price: 120,
    stock: 16,
    mark: "Standard",
    tags: ["B"],
    category: "Chirurgie Dentaire",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15")
  },
  {
    id: "16",
    ref: "SCEAU-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Sceau Fissure",
    description: "Prévention des caries sur les dents permanentes.",
    price: 80,
    new_price: 60,
    stock: 22,
    mark: "Basic",
    tags: ["A"],
    category: "Soins Préventifs",
    createdAt: new Date("2024-01-16"),
    updatedAt: new Date("2024-01-16")
  },
  {
    id: "17",
    ref: "URGENCE-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Urgence Dentaire",
    description: "Prise en charge rapide des douleurs aiguës.",
    price: 100,
    new_price: 90,
    stock: 9,
    mark: "Standard",
    tags: ["E"],
    category: "Services Spécialisés",
    createdAt: new Date("2024-01-17"),
    updatedAt: new Date("2024-01-17")
  },
  {
    id: "18",
    ref: "REHAB-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Réhabilitation Totale",
    description: "Restauration complète de l'esthétique et fonction dentaire.",
    price: 1500,
    new_price: 1350,
    stock: 3,
    mark: "Luxury",
    tags: ["E"],
    category: "Services Spécialisés",
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-18")
  },
  {
    id: "19",
    ref: "ANESTH-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Anesthésie Locale",
    description: "Gestion indolore des traitements dentaires.",
    price: 30,
    new_price: 25,
    stock: 40,
    mark: "Basic",
    tags: ["A"],
    category: "Services Spécialisés",
    createdAt: new Date("2024-01-19"),
    updatedAt: new Date("2024-01-19")
  },
  {
    id: "20",
    ref: "CONSULT-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Consultation",
    description: "Examen initial et conseils personnalisés.",
    price: 60,
    new_price: 50,
    stock: 50,
    mark: "Basic",
    tags: ["A"],
    category: "Soins Préventifs",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20")
  },
  {
    id: "21",
    ref: "CHIRURGIE-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Chirurgie Buccale",
    description: "Chirurgies mineures pour problèmes dentaires complexes.",
    price: 400,
    new_price: 380,
    stock: 13,
    mark: "Standard",
    tags: ["C"],
    category: "Chirurgie Dentaire",
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21")
  },
  {
    id: "22",
    ref: "COURONNE-PROV-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Couronne Provisoire",
    description: "Protéger temporairement vos dents après traitement.",
    price: 150,
    new_price: 130,
    stock: 19,
    mark: "Standard",
    tags: ["D"],
    category: "Prothèses",
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22")
  },
  {
    id: "23",
    ref: "BLANCH-LASER-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Blanchiment Laser",
    description: "Blanchiment rapide et efficace avec technologie laser.",
    price: 250,
    new_price: 200,
    stock: 17,
    mark: "Premium",
    tags: ["A"],
    category: "Services Spécialisés",
    createdAt: new Date("2024-01-23"),
    updatedAt: new Date("2024-01-23")
  },
  {
    id: "24",
    ref: "GOUTTIERES-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Gouttières Nocturnes",
    description: "Prévention du bruxisme durant la nuit.",
    price: 120,
    new_price: 100,
    stock: 21,
    mark: "Standard",
    tags: ["C"],
    category: "Orthodontie",
    createdAt: new Date("2024-01-24"),
    updatedAt: new Date("2024-01-24")
  },
  {
    id: "25",
    ref: "AIRFLOW-001",
    image: "https://img.medicalexpo.fr/images_me/photo-g/301158-18251063.webp",
    name: "Nettoyage Air Flow",
    description: "Élimination douce de la plaque et colorations.",
    price: 110,
    new_price: 95,
    stock: 28,
    mark: "Standard",
    tags: ["B"],
    category: "Soins Préventifs",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25")
  }
];

export async function GET() {
  return NextResponse.json(items);
} 